version: '3'

services:
  web:
    image: 'xploreproject_web'
    ports:
        - "80:80"
        - "443:443"
  auth:
    image: 'xploreproject_auth'
    ports:
        - "3030:3030"
  user:
    image: 'xploreproject_user'
    ports:
        - "3031:3030"
    environment:
      - DATABASE_URL=xplore.cb3sgsj6hke0.us-east-2.rds.amazonaws.com


